/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import datos.Conexion;
import datos.excepciones;
import java.sql.Connection;
import javax.swing.JOptionPane;
import logica.daousuarios;

/**
 *
 * @author DiWolf
 */
public class frm_login extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_login
     */
    daousuarios usuarios_ = new daousuarios();
    varGlobales var = new varGlobales();

    public frm_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_login = new javax.swing.JPanel();
        lbl_usuario = new javax.swing.JLabel();
        txt_usuarioLogin = new javax.swing.JTextField();
        lbl_contraseña = new javax.swing.JLabel();
        txt_passwordLogin = new javax.swing.JPasswordField();
        btn_ingresarLogin = new javax.swing.JButton();
        btn_cancelarLogin = new javax.swing.JButton();
        jbl_imagenLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_servidor = new javax.swing.JTextField();

        setTitle("Ingresar al Sistema");

        panel_login.setBackground(new java.awt.Color(255, 255, 255));
        panel_login.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar al Sistema"));

        lbl_usuario.setText("Usuario:");

        txt_usuarioLogin.setName("Usuario"); // NOI18N

        lbl_contraseña.setText("Password:");

        txt_passwordLogin.setName("Contraseña"); // NOI18N

        btn_ingresarLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        btn_ingresarLogin.setText("Ingresar");
        btn_ingresarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarLoginActionPerformed(evt);
            }
        });

        btn_cancelarLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/101.png"))); // NOI18N
        btn_cancelarLogin.setText("Cancelar");
        btn_cancelarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarLoginActionPerformed(evt);
            }
        });

        jbl_imagenLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login Manager.png"))); // NOI18N

        jLabel1.setText("Servidor");

        javax.swing.GroupLayout panel_loginLayout = new javax.swing.GroupLayout(panel_login);
        panel_login.setLayout(panel_loginLayout);
        panel_loginLayout.setHorizontalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jbl_imagenLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_usuario, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_contraseña, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_passwordLogin)
                            .addComponent(txt_usuarioLogin)
                            .addComponent(txt_servidor)))
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addContainerGap(166, Short.MAX_VALUE)
                        .addComponent(btn_ingresarLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancelarLogin)))
                .addGap(16, 16, 16))
        );
        panel_loginLayout.setVerticalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_usuario)
                            .addComponent(txt_usuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_contraseña)
                            .addComponent(txt_passwordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_servidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbl_imagenLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ingresarLogin)
                    .addComponent(btn_cancelarLogin))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 398, 174);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarLoginActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        int resultado = JOptionPane.showConfirmDialog(panel_login, "¿Está seguro que desea salir?", "Salir", JOptionPane.YES_NO_OPTION);
        if (resultado == 0) {
            System.exit(0);
        } else {
        }

    }//GEN-LAST:event_btn_cancelarLoginActionPerformed

    private void btn_ingresarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarLoginActionPerformed
        // TODO add your handling code here:
        Conexion.servidor = (txt_servidor.getText());
        if (txt_usuarioLogin.getText().isEmpty()) {
            excepciones.CamposVacios(txt_usuarioLogin.getName());
        }
        if (txt_passwordLogin.getText().isEmpty()) {
            excepciones.CamposVacios(txt_passwordLogin.getName());
        } else {
            boolean x = usuarios_.Login(txt_usuarioLogin.getText(), txt_passwordLogin.getText());
            if (x == true) {
                excepciones.setPermisos(1);
                this.dispose();
            } else {
                excepciones.ErrorValidarUsuario();
            }
        }
    }//GEN-LAST:event_btn_ingresarLoginActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelarLogin;
    private javax.swing.JButton btn_ingresarLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jbl_imagenLogin;
    private javax.swing.JLabel lbl_contraseña;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JPanel panel_login;
    private javax.swing.JPasswordField txt_passwordLogin;
    private javax.swing.JTextField txt_servidor;
    private javax.swing.JTextField txt_usuarioLogin;
    // End of variables declaration//GEN-END:variables
}
