package vistas;

import datos.excepciones;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author DiWolf
 */
public class frm_principal extends javax.swing.JFrame {

    /**
     * Creates new form frm_principal
     */
//    frm_principal principal = new frm_principal();
    frm_login lg = new frm_login();
    varGlobales vb = new varGlobales();

    public frm_principal() {
        initComponents();
        //  this.prueba();
        escritorio.add(lg);
        // activaOpciones();
        lg.show();
    }

    //comprobar banderas
    public void activaOpciones(int bandera) {
        switch (bandera) {
            case 1: {
                btn_contactos.enable(true);
            }
            break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btn_correo = new javax.swing.JButton();
        btn_contactos = new javax.swing.JButton();
        btn_ingresarSistema = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        menu_mailnoentregado = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jfile_salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_perfil = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmenu_usuarios = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adagio Mail.");
        setIconImage(new ImageIcon(getClass().getResource("logoSECAY.ico")).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                confirmacion(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setBorderPainted(false);
        jToolBar1.setEnabled(false);
        jToolBar1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jToolBar1ComponentAdded(evt);
            }
        });

        btn_correo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/27-Edit Text.png"))); // NOI18N
        btn_correo.setText("Redactar");
        btn_correo.setFocusable(false);
        btn_correo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_correo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_correoActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_correo);

        btn_contactos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contacts_book-16.png"))); // NOI18N
        btn_contactos.setText("Direcciones");
        btn_contactos.setFocusable(false);
        btn_contactos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_contactos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_contactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_contactosActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_contactos);

        btn_ingresarSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        btn_ingresarSistema.setText("Ingresar");
        btn_ingresarSistema.setFocusable(false);
        btn_ingresarSistema.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ingresarSistema.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_ingresarSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarSistemaActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_ingresarSistema);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        escritorio.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(escritorio);

        jMenu1.setText("Archivo");

        jMenu3.setText("Correos");

        jMenuItem2.setText("Nuevo Correo ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        menu_mailnoentregado.setText("Correo no entregado");
        menu_mailnoentregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_mailnoentregadoActionPerformed(evt);
            }
        });
        jMenu3.add(menu_mailnoentregado);

        jMenu1.add(jMenu3);
        jMenu1.add(jSeparator1);

        jfile_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Log Out.png"))); // NOI18N
        jfile_salir.setText("Salir");
        jfile_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfile_salirActionPerformed(evt);
            }
        });
        jMenu1.add(jfile_salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Configuraciones");

        menu_perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        menu_perfil.setText("Mi Perfíl");
        menu_perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_perfilActionPerformed(evt);
            }
        });
        jMenu2.add(menu_perfil);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/list_bullets.png"))); // NOI18N
        jMenu4.setText("Administración");

        jmenu_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jmenu_usuarios.setText("Usuarios");
        jmenu_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_usuariosActionPerformed(evt);
            }
        });
        jMenu4.add(jmenu_usuarios);

        jMenuItem5.setText("Configuraciones del Sistema");
        jMenu4.add(jMenuItem5);

        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToolBar1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jToolBar1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jToolBar1ComponentAdded

    private void jfile_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfile_salirActionPerformed
        // TODO add your handling code here:
        this.dispose(); //Cerrar la venta.
    }//GEN-LAST:event_jfile_salirActionPerformed

    private void btn_contactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_contactosActionPerformed
        // TODO add your handling code here:..
        //  if (this.escritorio.getComponentCount() == 0) {
        if (excepciones.getPermisos() == 1) {
            frm_contactos contactos = new frm_contactos();
            escritorio.add(contactos);
            contactos.show(true);
        } else {
            excepciones.ErrorAcceso();
        }
        // }
    }//GEN-LAST:event_btn_contactosActionPerformed

    private void btn_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_correoActionPerformed
        // TODO add your handling code here:
        //   if (this.escritorio.getComponentCount() == 0) {
        frm_correo correo = null;
        if (excepciones.getPermisos() == 1) {
            try {
                correo = new frm_correo();
            } catch (IOException ex) {
                Logger.getLogger(frm_principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            escritorio.add(correo);
            correo.show();
        } else {
            excepciones.ErrorAcceso();
        }
    }//GEN-LAST:event_btn_correoActionPerformed

    private void btn_ingresarSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarSistemaActionPerformed
        // TODO add your handling code here:
        escritorio.add(lg);
        lg.show();
    }//GEN-LAST:event_btn_ingresarSistemaActionPerformed

    private void menu_perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_perfilActionPerformed
        // TODO add your handling code here:
        frm_perfil perfil = new frm_perfil();
        if (excepciones.getPermisos() == 1) {
            escritorio.add(perfil);
            perfil.show();
        } else {
            excepciones.ErrorAcceso();
        }
    }//GEN-LAST:event_menu_perfilActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            // TODO add your handling code here:
            frm_correo correo = new frm_correo();
            escritorio.add(correo);
            correo.show();
        } catch (IOException ex) {
            Logger.getLogger(frm_principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmenu_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_usuariosActionPerformed
        // TODO add your handling code here:
        frm_administrador admin = new frm_administrador();
        
        escritorio.add(admin);
        admin.show(true);
    }//GEN-LAST:event_jmenu_usuariosActionPerformed

    private void confirmacion(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_confirmacion
        // TODO add your handling code here:
        int resultado = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea salir?", "Salir", JOptionPane.YES_NO_OPTION);
        if (resultado == 0) {
            System.exit(0);
        } else {
            //frm_principal.
        }
    }//GEN-LAST:event_confirmacion

    private void menu_mailnoentregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_mailnoentregadoActionPerformed
        // TODO add your handling code here:
        frm_correonoEntregado noentregado = null; 
        try {
            noentregado = new frm_correonoEntregado();
        } catch (IOException ex) {
            Logger.getLogger(frm_principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        escritorio.add(noentregado);
        noentregado.show();
    }//GEN-LAST:event_menu_mailnoentregadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            try {
                // Set System L&F
                UIManager.setLookAndFeel(
                        UIManager.getSystemLookAndFeelClassName());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(frm_principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(frm_principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(frm_principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (UnsupportedLookAndFeelException e) {
            // handle exception
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_contactos;
    private javax.swing.JButton btn_correo;
    private javax.swing.JButton btn_ingresarSistema;
    public javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem jfile_salir;
    private javax.swing.JMenuItem jmenu_usuarios;
    private javax.swing.JMenuItem menu_mailnoentregado;
    private javax.swing.JMenuItem menu_perfil;
    // End of variables declaration//GEN-END:variables
}
